# fly.toml app configuration file generated for remix-recipes on 2023-07-08T18:01:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-recipes"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
