# fly.toml app configuration file generated for cart-web on 2023-09-13T21:56:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cart-web"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
